### PR TITLE
Introduce autoloader

### PR DESCRIPTION
**Pull request by szepeviktor**
This is an inspirational PR related to #25

I work in complete and comfy PHP environment.
Currently I'm missing essentials.

- namespaces (available in ancient PHP 5)
- static analysis

Source: https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wp-install/wordpress-autoloader.php

### CODE REVIEW

**Comment by smileBeda** [comment]
I don't like to remove the admin/public class file and put it into the includes.

I am aware it is for simplicity to allow the autoloader finding the classes in _one_ folder, which is why I passed an array of source folders in the (tiny) autoloader I made here: https://github.com/TukuToi/tukutoi-cp-directory-integration/blob/f91ec328109c6f4b6948cd9414b4567fc77deed1/includes/class-cp-plgn-drctry-loader.php#L191

The reason to put the files in distinct folders of course is a nuisance, but it helps (I think) to separate the files by where they act (backend or front end).

Anything speaking against this from your point of view?

**Comment by szepeviktor** [comment]
> Anything speaking against this from your point of view?

I work in complete and comfy PHP environment described in https://github.com/szepeviktor/small-project
Breaking down that down to steps and evaluating each one is above my pay grade :)

**Comment by szepeviktor** [comment]
@smileBeda Actually `small-project` is the fruit 🍇 of 7 years of participation in the WordPress ecosystem. It is an intention _to leave legacy technologies behind_.

**Comment by szepeviktor** [comment]
@smileBeda I leave using an autoloader 101% up to you.

**Comment by smileBeda** [comment]
Hi @szepeviktor - actually my latest Pushes to main are preparation to release a _last_ version before a full redo of the boilerplate, which will include autoloader (and a full new folder structure, which is why I need to first close off the existing "version" and then start with a completely new structure)

Thank you!

**Comment by szepeviktor** [comment]
I strongly encourage you to leave legacy technologies behind.
WordPress lives it life in the far past. But do not let that be a reason to use PHP as a template engine. At 7.0 PHP starts to be a programming language.

Here is a [_What to avoid_ list](https://github.com/szepeviktor/starter-plugin/blob/master/README.md#what-to-avoid).

**Pull request closed without merging**
