### PR TITLE
Add PHPCS Github Action

### PR DESCRIPTION
**Pull request by w3bdesign**
With Wordpress coding standards by default

### CODE REVIEW

**Comment by w3bdesign** [comment]
@TukuToi

**Comment by TukuToi** [comment]
Just trying to figure out how I'll merge this without conflicts, since you branched from the master and not from develop, which is ahead currently.

As soon I figure out how to do that conflict less, I will merge this here into (hopefully first) develop, then into master once I test develop thoroughly.

**Comment by bahiirwa** [comment]
@w3bdesign Thats's a cool upgrade. Could you rebase for this and push upstream?

**Comment by TukuToi** [comment]
I think I just merged it to Develop successfully and without conflicts.
See https://github.com/TukuToi/better-wp-plugin-boilerplate/tree/develop

As soon I am stable with the develop, I will merge that to master, which will conclude the cycle.
Anything I miss?
Sorry, it is the first time I handle a community interaction on my repos, thus very likely I miss something :)

**Comment by bahiirwa** [comment]
No. That's well handled. I was just following up with master.

**Comment by TukuToi** [comment]
Hi @w3bdesign I wanted to merge develop to master today which would bring the PHPCS into it, however, the check did not pass due to https://github.com/TukuToi/better-wp-plugin-boilerplate/pull/5/checks?check_run_id=3044458770
`[ERROR] Secret `GH_BOT_TOKEN` or `VAULT_TOKEN` is missing. Please add it to this action for proper execution.`

It then links to https://github.com/rtCamp/action-phpcs-code-review#github-token-creation, where it says to generate a Token.
I can also see in your commit that there's a `GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}` line where I suppose would add the Token.

However here's the thing:
Git says the token should be created by a "Bot Account". Do you know what that is?
Second, after I generate a token from https://github.com/settings/tokens (as my own account, because I am or have no bot), it says:
```
Personal access tokens
Generate new token Revoke all
Tokens you have generated that can be used to access the GitHub API.

Make sure to copy your personal access token now. You won’t be able to see it again!
(TOKEN HERE)

Personal access tokens function like ordinary OAuth access tokens. They can be used instead of a password for Git over HTTPS, or can be used to authenticate to the API over Basic Authentication.
```

I am not sure I am comfortable adding a Token that acts like a authentication _in stead_ of PWDS or else, to a public file.
Sorry the trouble, I have literally no idea how to proceed, what options to select when creating the token, and how safe this is :)

Do you have experience with this?

**Comment by w3bdesign** [comment]
@TukuToi 

It's been some time since I worked on this, but what I remember doing was creating a new Github account that I used as a bot account.

Basically you just need to follow the instrcutions here: https://github.com/rtCamp/action-phpcs-code-review#github-token-creation

Also you need to add that token to the repository secrets. I am attaching a screenshot to show you where I added it myself to a Wordpress repository:

bilde

**Comment by TukuToi** [comment]
OK thanks, that did it!

Now... There's a few errors which I guess we have to sort out.

Note that on my local, I use WPCS and there are 0 errors.
However the bot found 19 warnings.
Here's the report:
https://github.com/TukuToi/better-wp-plugin-boilerplate/pull/5#pullrequestreview-704770842

I have commented on each _type_ of error as they repeat.
I would like some input on them so I can either fix, or somehow ignore.

Thanks for all the super helpful help!

**Comment by w3bdesign** [comment]
@tukutoi

Not sure if I would call myself a PHPCS/WordPress expert, but I will try my best to make some comments and suggestions in the pull request.

**Comment by smileBeda** [comment]
@bahiirwa - perhaps you have a clue how to solve this

This entire workflow works only for PRs from _within the repo_, not when it is a PR from a fork.
See also https://github.com/rtCamp/action-phpcs-code-review/issues/11

Basically, the entire GitHub consist of forks and forks will PR back to upstream.
Yet it seems GitHub actions - requiring a Token - will never work with fork-PRs

In every case a user submits a PR to this (or any other) repo, the workflow/action that we added here (Coding standards) will fail with `[ERROR] Secret `GH_BOT_TOKEN` or `VAULT_TOKEN` is missing. Please add it to this action for proper executio`
Whenever the PR is from within (not a fork) it will work

How can it be that the very main purpose of GitHub is basically destroyed when adding such workflows?
I am pretty sure we did something wrong here. Perhaps you have some insight you can share?

Thank You!

**Pull request merged**
